### ISSUE TITLE
Have usage/testing decrease chance of failure

### ISSUE THREAD

**Issue by 602p** [Ippo343/DangIt#98]
Esoteric1 suggested this in the forum thread.

Very long-term.

**Comment by Ippo343** [comment]
I am against usage improving reliability.
Time is money: so in the end, it's not too different from paying to improve the reliability of a part. Even worse, the more you use your favourite engine, the more you are encouraged to use it (as it would become also the most reliable), thus eliminating the restrictions which are the whole point of this mod.

As for testing, I'd really do it the other way around: rather than increasing reliability after testing, I'd give a huge reliability nerf to test parts. Right now if you get the contract to test the NERVAs, you can basically cheat the game by using them to go everywhere without having unlocked them yet (as the game does not restrict your use).
In my vision, test parts are still experimental, and thus they should be much *less* reliable than they are once unlocked.

@602p , what do you think?

**Comment by 602p** [comment]
This is a good point.

I'll close this until we can figure out a more balanced solution to this general idea.
